### ISSUE TITLE
AttributeError: 'bytes' object has no attribute 'encode'

### ISSUE THREAD

**Issue by MikeAnderson-E16247** [LukeMurphey/splunk-file-info#2]
Hey, I'm getting the following when I try and index the meta data for a file:
`2022-03-02 09:33:28,946 ERROR Execution failed
Traceback (most recent call last):
  File "/opt/splunk/etc/apps/file_meta_data/bin/modular_input.zip/modular_input/modular_input_base_class.py", line 1095, in execute
    self.do_run(in_stream, log_exception_and_continue=True)
  File "/opt/splunk/etc/apps/file_meta_data/bin/modular_input.zip/modular_input/modular_input_base_class.py", line 976, in do_run
    self.run(stanza, cleaned_params, input_config)
  File "/opt/splunk/etc/apps/file_meta_data/bin/file_meta_data.py", line 641, in run
    file_filter=file_filter)
  File "/opt/splunk/etc/apps/file_meta_data/bin/file_meta_data.py", line 187, in get_files_data
    file_path = file_path.encode("utf-8")
AttributeError: 'bytes' object has no attribute 'encode'
`
I've tried w/ and w/out a filter w/ the same results. Is this something you can help with?

Thanks much

**Comment by LukeMurphey** [comment]
I'm pretty sure I have a fix for this. I will upload a new version tonight. I'll let you when I get it ready (it is going through final testing).

**Comment by LukeMurphey** [comment]
I uploaded version 1.4.6 to Splunkbase and to the Github releases page.
